# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Basics for Ph.D Survival
author: SeungHeon Doh
logo: images/logo.png
execute:
  execute_notebooks: "off"

# # Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_admonition
    - html_image

launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  thebe: true
  binderhub_url: "https://mybinder.org"

html:
  favicon: images/favicon.ico
  home_page_in_navbar  : false
  use_repository_button: true
  google_analytics_id: UA-208590538-1

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/seungheondoh/basic  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)
